spring.application.name=desenvolvimento
server.port = 8085
spring.datasource.url=jdbc:mysql://localhost:3307/db_ponto_agro?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=8f1e6c2a9b4d7f0e3c5a8b1d4f7e0c3a6b9d2f5e8c1a4b7d0f3e6c9a2b5d8f1e
app.jwt.expiracao-minutos=480